name: Multimixer-128

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Run Known Answer Tests
      run: cargo test --lib
    - name: Run Examples
      run: cargo run --example multimixer_128
